config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ec_site.urls')),
    path('sales_management/', include('sales_management.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ec_site/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.contrib.auth import views as django_auth_views

app_name = 'ec_site'

urlpatterns = [
    path('top/', views.Lp.as_view(), name='lp'),
    path('items/', views.ItemList.as_view(), name = 'item_list'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name = 'item_detail'),
    path('', views.Login.as_view(), name = "login"),
    path('logout', django_auth_views.LogoutView.as_view(), name = "logout"),
    path('sign_up/', views.SignUp.as_view(), name='sign_up'),
    path('sign_up/confirm', views.SignUpComfirm.as_view(), name='sign_up_confirm'),
    path('sign_up/done/<token>', views.SignUpDone.as_view(), name='sign_up_done'),
    path('cart/<int:pk>', views.ShoppingCartDetail.as_view(), name = 'cart'),
    path('ajax_amount/', views.update_cart_item_amount, name = 'update_cart_item_amount'),
    path('ajax_delete/', views.delete_cart_item, name = 'delete_cart_item'),
    path('order-confirmation/<int:pk>/', views.OrderConfirmation.as_view(), name='order-confirmation'),
    path('payment-confirmation/', views.OrderPayConfirmation.as_view(), name='payment-confirmation'),
]

ec_site/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User
from django.core.exceptions import ValidationError


class LoginForm(AuthenticationForm):
    """ログインフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class SignUpForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email', 'name',)
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ShoppingCartDetailForm(forms.Form):

    name = forms.CharField(label="氏名")
    email = forms.EmailField(label="メールアドレス")
    zip_code = forms.RegexField(
        label="郵便番号",
        regex=r'^[0-9]+$',
        max_length=8,
        help_text = '※郵便番号のハイフン「-」なしでも可',
        widget=forms.TextInput(attrs={
            'onKeyUp' : "AjaxZip3.zip2addr(this,'','address','address')"}),)
    address = forms.CharField(label="住所",help_text="※郵便番号を入力すると市区町村まで自動で入力されます。")
    
    

ec_site/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import *
from django.contrib.auth.views import LoginView
from .forms import *
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest 
from django.core.signing import BadSignature, SignatureExpired, dumps, loads 
from django.urls import reverse 
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template 
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
import json


class Lp(generic.ListView):
    model = Product
    template_name = 'ec_site/lp.html'
    queryset = Product.objects.all()
    

class ItemList(generic.ListView):
    model = Product
    template_name = 'ec_site/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] != None:
            q = self.request.GET['q']
            print("q=", q)
            products = products.filter(name__icontains = q)
        return products

    def get_context_data(self, **kwargs):
       context = super(ItemList, self).get_context_data(**kwargs)
       context['category_list'] = Category.objects.all()
       return context

 
class CategoryView(generic.ListView):
    """カテゴリのリンククリック"""

    template_name = 'ec_site/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] != None:
            q = self.request.GET['q']
            print("q=", q)
            products = products.filter(name__icontains = q)
        else:
            """カテゴリでの絞り込み"""
            category_name = self.kwargs['category']
            self.category_name = Category.objects.get(name=category_name)
            products = Product.objects.filter(category=self.category_name)
        return products

    def get_context_data(self, **kwargs):
       context = super(CategoryView, self).get_context_data(**kwargs)
       context['category_list'] = Category.objects.all()
       return context


class ItemDetail(generic.DetailView):
    model = Product
    template_name = 'ec_site/item_detail.html'


    def get_context_data(self, **kwargs):
       context = super(ItemDetail, self).get_context_data(**kwargs)
       context['category_list'] = Category.objects.all()
       return context


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'ec_site/login.html'


class SignUp(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'ec_site/sign_up.html'
    form_class = SignUpForm
   
    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        """
        get_template　→ temptate.render(context)

        テンプレートファイルを読み込みんでからコンテキストを注入する処理になっております。
        ここでセットしたコンテキスト(辞書型のオブジェクト)はテンプレート側から{{ xxx }}
        のようにアクセスできる。
        """
        subject_template = get_template('ec_site/mail_template/sign_up/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('ec_site/mail_template/sign_up/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        messages.success(self.request, '本登録用リンクを送付しました')
        return  HttpResponseRedirect(reverse('ec_site:sign_up_confirm'))


class SignUpDone(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'ec_site/sign_up_done.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内


    """
    getメソッドは、クライアントからこのビューに対してHTTP GETが送られた際に実行される関数
    URLについているトークンが一定時間以内に生成されたものかを検証し、正当であると判断したらテンプレート表示、
    正しくなければ(時間切れ等)HTTPエラーを返すようにカスタマイズ
    全て正常に処理が進んだ場合はsuper().get(request, **kwargs)で親クラスのgetメソッドを呼んでいる)
    """
    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    
                    # [7-1]追加 ここから
                    # ユーザ処理完了後にそのユーザにひもづくカートも生成
                    his_cart = ShoppingCart()
                    his_cart.user = user
                    his_cart.save()
                    
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class SignUpComfirm(generic.TemplateView):
    """ユーザ登録確認画面"""
    template_name = 'ec_site/sign_up_confirm.html'


class ShoppingCartDetail(LoginRequiredMixin, generic.DetailView):
    model = ShoppingCart
    template_name = "ec_site/shopping_cart.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['form'] = ShoppingCartDetailForm()
        return self.render_to_response(context)
        
        
    def post(self, request, *args, **kwargs):

        if 'product_pk' in self.request.POST and self.request.POST['product_pk'] != None:

            user = request.user
            product_pk = request.POST.get('product_pk')
            product = Product.objects.get(pk = product_pk)
            amount = request.POST.get('amount')

            exist = ShoppingCartItem.objects.filter(cart__user = user).filter(product = product)

            # すでにカートに存在する商品の場合は個数をインクリメント
            if len(exist) > 0:
                current_amount = exist[0].amount
                exist[0].amount = current_amount + int(amount)
                exist[0].save()
            else:
                new_cart_item = ShoppingCartItem()
                new_cart_item.cart = request.user.cart
                new_cart_item.product = product
                new_cart_item.amount = int(amount)
                new_cart_item.save()
            return HttpResponseRedirect(reverse('ec_site:cart',  kwargs={'pk': self.get_object().pk}))
        
        if 'name' in self.request.POST and self.request.POST['name'] != None:
            #注文画面下部のフォームで入力されたユーザ情報を取得
            name = request.POST.get('name')
            email = request.POST.get('email')
            address = request.POST.get('address')
            zip_code = request.POST.get('zip_code')

            #注文データを生成 
            order = OrderItem.objects.create(
                user=User.objects.get(email=request.user.cart),
                name=name,
                email=email,
                address=address,
                zip_code=zip_code
                )

            #order_items = {'items': []}  #オーダー情報の格納辞書
            cart_items = ShoppingCartItem.objects.filter(cart__user__email=request.user.cart)
            #オーダーデータに紐づく明細データを生成
            for item in cart_items:
                OrderItemDetail.objects.create(
                            invoice = OrderItem.objects.get(pk= order.pk),
                            product = item.product,
                            #unit_price = item.product.price,
                            quantity = item.amount 
                          )

            cart_datas = ShoppingCart.objects.filter(user = User.objects.get(email=request.user.cart))
            total_price = [data.total_price for data in cart_datas]

            order_items = {'items': []}  #オーダー情報の格納辞書
            for item in cart_items:
                item_data = {
                    'id': item.product.pk,
                    'name': item.product,
                    }
                order_items['items'].append(item_data)

            item_ids = []
            #製品名のPKを取得
            for item in order_items['items']:
                item_ids.append(item['id'])
            #注文データに商品情報を追加
            order.items.add(*item_ids)
            order.price = total_price[0]
            order.save()

            #return  HttpResponseRedirect(reverse('ec_site:sign_up_confirm'))
            return redirect('ec_site:order-confirmation', pk=order.pk)


class OrderConfirmation(generic.TemplateView):

    def get(self, request, pk, *args, **kwargs):
        order = OrderItem.objects.get(pk=pk)
        order_details = OrderItem.objects.get(pk= pk).orderitemdetail_set.all()
        print("order=", order)
        context = {
            'title': '注文日時：' + order.created_on.strftime('%Y/%m/%d %H:%M:%S'),
            'pk': order.pk,
            'items': order.items.all(),
            'price': order.price,
            'order_details': order_details
        }
        return render(request, 'ec_site/order_confirmation.html', context)


    def post(self, request, pk, *args, **kwargs):
        data = json.loads(request.body)
        print("postメソッドが呼ばれました")

        #注文データのisPaidをTrueに更新
        if data['isPaid']:
            print("if data!!")
            order = OrderItem.objects.get(pk=pk)

templates/ec_site/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<style>
    body{ 
        padding-top: 60px; 
    }
</style>


    <title>ECサイト</title>

<body>
    <header class="section-header fixed-top">
        <section class="header-main">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <a href="{% url 'ec_site:lp' %}">
                            <div class="brand-wrap">
                                <img class="logo" src="{% static 'images/shopping-cart.png' %}">
                                <h2 class="logo-text text-white">ECサイト Unusual</h2>
                            </div> <!-- brand-wrap.// -->
                        </a>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <form method="get" action="{% url 'ec_site:item_list' %}" class="search-wrap">
                            <div class="input-group">
                                <input name="q" type="text" class="form-control" placeholder="商品検索">
                                <div class="input-group-append">
                                    <button id="id_search_button" class="btn btn-warning" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-lg-3 col-sm-6">
                        <div class="widgets-wrap d-flex justify-content-end">
                            {% if user.is_authenticated %}
                            <div class="widget-header icontext">
                                <a href="{% url 'ec_site:cart' user.cart.pk %}" class="icontext">
                                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-shopping-cart"></i></div>
                                    <div class="text-wrap">
                                        <small>カート</small>
                                        <span>{{ user.cart.item_count|default_if_none:"0" }}商品</span>
                                    </div>
                                </a>
                            </div> <!-- widget .// -->
                            {% endif %}
                            <!-- [5-6] ログイン状態による分岐追加 ここから -->
                            <div class="widget-header icontext">
                                <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                <div class="text-wrap">
                                    {% if user.is_authenticated %}
                                    <small>{{user.name}}さん</small>
                                    <span><a href="{% url 'ec_site:logout' %}">Logout</a></span>
                                    {% else %}
                                    <small>ゲスト</small>
                                    <span><a href="{% url 'ec_site:login' %}">Login</a></span>
                                    {% endif %}
                                </div>
                            </div> <!-- widget  dropdown.// -->
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
    </header> <!-- section-header.// -->
    <div class="container" style="padding: 2rem">
        {% block content %}{% endblock %}
    </div>
    <footer class="py-1 bg-dark text-light">
        <div class="container text-center">
          <!-- ナビゲーション -->
          <ul class="nav justify-content-center mb-3">
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'ec_site:lp' %}">Top</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'ec_site:item_list' %}">商品一覧</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'ec_site:cart' user.cart.pk %}">Cart</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-white" href="contact.html">Contact</a>
            </li>
          </ul>
          <!-- /ナビゲーション -->
          <p><small>Copyright &copy;2021 Unusual, All Rights Reserved.</small></p>
        </div>
      </footer>

    <script type="text/javascript">
        function getCookie(name) {
           var cookieValue = null;
           if (document.cookie && document.cookie !== '') {
               var cookies = document.cookie.split(';');
               for (var i = 0; i < cookies.length; i++) {
                   var cookie = jQuery.trim(cookies[i]);
                   // Does this cookie string begin with the name we want?
                   if (cookie.substring(0, name.length + 1) === (name + '=')) {
                       cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                       break;
                   }
               }
           }
           return cookieValue;
       }

       var csrftoken = getCookie('csrftoken');

       function csrfSafeMethod(method) {
           // these HTTP methods do not require CSRF protection
           return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
       }

       $.ajaxSetup({
           beforeSend: function (xhr, settings) {
               if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                   xhr.setRequestHeader("X-CSRFToken", csrftoken);
               }
           }
       });   
   </script>
   
    {% block scripts %}{% endblock %}
</body>

</html>

templates/ec_site/item_list.html
{% extends "ec_site/base.html" %}
{% block content %}
{% load static %}
<!-- カテゴリ一覧の表示 -->
{% include 'ec_site/widgets/side_category.html' %}

<div class="row-sm  mt-4">
    {% for object in object_list %}

    <div class="col-md-3">
        <figure class="card card-product">
            <div class="img-wrap"> <img src="{{ object.thumbnail.url }}"></div>
            <figcaption class="info-wrap">
                <h6 class="title "><a href="{% url 'ec_site:item_detail' object.pk %}">{{ object.name }}</a></h6>
                <div class="price-wrap">
                    <span class="price-new">{{ object.price }}円</span>
                </div> <!-- price-wrap.// -->

            </figcaption>
        </figure> <!-- card // -->
    </div> <!-- col // -->

    {% endfor %}
</div>
{% endblock %}

templates/ec_site/login.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="ja">

<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- Primary Meta Tags -->
<title>Volt Premium Bootstrap Dashboard - Sign in page</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Volt Premium Bootstrap Dashboard - Sign in page">
<meta name="author" content="Themesberg">
<meta name="description" content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta name="keywords" content="bootstrap 5, bootstrap, bootstrap 5 admin dashboard, bootstrap 5 dashboard, bootstrap 5 charts, bootstrap 5 calendar, bootstrap 5 datepicker, bootstrap 5 tables, bootstrap 5 datatable, vanilla js datatable, themesberg, themesberg dashboard, themesberg admin dashboard" />
<link rel="canonical" href="https://themesberg.com/product/admin-dashboard/volt-premium-bootstrap-5-dashboard">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://demo.themesberg.com/volt-pro">
<meta property="og:title" content="Volt Premium Bootstrap Dashboard - Sign in page">
<meta property="og:description" content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta property="og:image" content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://demo.themesberg.com/volt-pro">
<meta property="twitter:title" content="Volt Premium Bootstrap Dashboard - Sign in page">
<meta property="twitter:description" content="Volt Pro is a Premium Bootstrap 5 Admin Dashboard featuring over 800 components, 10+ plugins and 20 example pages using Vanilla JS.">
<meta property="twitter:image" content="https://themesberg.s3.us-east-2.amazonaws.com/public/products/volt-pro-bootstrap-5-dashboard/volt-pro-preview.jpg">

<!-- Favicon -->
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/img/favicon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'assets/img/favicon/site.webmanifest' %}">
<link rel="mask-icon" href="{% static 'assets/img/favicon/safari-pinned-tab.svg' %}" color="#ffffff">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Sweet Alert -->
<link type="text/css" href="{% static 'vendor/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">

<!-- Notyf -->
<link type="text/css" href="{% static 'vendor/notyf/notyf.min.css" rel="stylesheet">

<!-- Volt CSS -->
<link type="text/css" href="{% static '/css/volt.css' %}" rel="stylesheet">

<!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->

</head>

<body>

    <!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->
    

    <main>

        <!-- Section -->
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <p class="text-center">
                    <a href="{% url 'ec_site:lp' %}" class="d-flex align-items-center justify-content-center">
                        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                        TOPへ戻る
                    </a>
                </p>
                <div class="row justify-content-center form-bg-image" data-background-lg="../../assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">ログオン画面</h1>
                            </div>
                            <form action="" class="mt-4" method="POST">
                                <!-- Form -->
                                {% csrf_token %}
                      
                                {% for field in form %}
                                {% if field.label == "メールアドレス" %}
                                <div class="form-group mb-4">
                                    <label for="user">{{ field.label }}</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                                        </span>
                                
                                        {% render_field field class="form-control" placeholder="ユーザ名を入力" %}
                                       <!--  <input type="text" class="form-control" placeholder="ユーザ名を入力"> -->
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                {% elif field.label == "パスワード" %}
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">{{ field.label }}</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                            </span>

                                            {% render_field field class="form-control" placeholder="パスワードを入力" %}
                                           <!--  <input type="password" placeholder="パスワードを入力" class="form-control" id="password" required> -->
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                  
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                  <div class="alert alert-danger" role="alert">
                                    <p>{{ error | linebreaksbr}}</p>
                                  </div>
                                {% endfor %}
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-gray-800">ログイン</button>
                                </div>
                            </form>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    アカウント未登録の方→
                                    <a href="{% url 'ec_site:sign_up' %}" class="fw-bold text-info">アカウントを作成する</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <!-- Core -->
<script src="{% static 'vendor/@popperjs/core/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<!-- Vendor JS -->
<script src="{% static 'vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>

<!-- Slider -->
<script src="{% static 'vendor/nouislider/distribute/nouislider.min.js' %}"></script>

<!-- Smooth scroll -->
<script src="{% static 'vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

<!-- Charts -->
<script src="{% static 'vendor/chartist/dist/chartist.min.js' %}"></script>
<script src="{% static 'vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

<!-- Datepicker -->
<script src=".{% static 'vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Sweet Alerts 2 -->
<script src="{% static 'vendor/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js' %}"></script>

<!-- Vanilla JS Datepicker -->
<script src="{% static 'vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

<!-- Notyf -->
<script src="{% static 'vendor/notyf/notyf.min.js' %}"></script>

<!-- Simplebar -->
<script src="{% static 'vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="{% static 'assets/js/volt.js' %}"></script>

    
</body>

</html>

templates/ec_site/order_pay_confirmation.html
{% extends "ec_site/base.html" %}
{% block content %}

<div class="container mb-5">
    <div class="row justify-content-center mt-1">
        <div class="col-md-5 col-sm-12 p-4 text-center">
            <h1>決済が完了しました!</h1>
            <a class="btn btn-primary mb-3 mt-5" href="{% url 'ec_site:lp' %}" role="button">TOPページへ戻る</a>
        </div>
    </div>
</div>
{% endblock content %}